# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('artifact_id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_type_id', models.IntegerField()),
                ('foreign_id', models.IntegerField()),
            ],
            options={
                'db_table': 'artifact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'artifact_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtifactType',
            fields=[
                ('artifact_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('artifact_type_name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'artifact_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
    ]
